export const ADD_ARTICLE = "ADD_ARTICLE";
export const AUTH_USER_SET = "AUTH_USER_SET";

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const TEST_SUCCESS = 'TEST_SUCCESS'
export const TEST_FAILURE = 'TEST_FAILURE'
export const TOKEN_RECOVER = 'TOKEN_RECOVER'
export const USER_RECOVER = 'USER_RECOVER'
export const USER_RETRIEVE = 'USER_RETRIEVE'
export const SESSION_RECOVER = 'SESSION_RECOVER'
export const CLIENT_LOGIN_SUCCESS = 'CLIENT_LOGIN_SUCCESS'
export const CLIENT_LOGOUT_SUCCESS = 'CLIENT_LOGOUT_SUCCESS'
export const CLIENT_TOKEN_RECOVER = 'CLIENT_TOKEN_RECOVER'
export const CLIENT_USER_RECOVER = 'CLIENT_USER_RECOVER'
export const CLIENT_SESSION_RECOVER = 'CLIENT_SESSION_RECOVER'

export const LOADING_START = 'LOADING_START'
export const LOADING_END = 'LOADING_END'
export const SET_LOADER = 'SET_LOADER'

