export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const TOKEN_RECOVER = 'TOKEN_RECOVER';
export const TEST_SUCCESS = 'TEST_SUCCESS';
export const TEST_FAILURE = 'TEST_FAILURE';
export const USER_RECOVER = 'USER_RECOVER';
export const USER_RETRIEVE = 'USER_RETRIEVE';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
export const SET_LOADER = 'SET_LOADER';

export const NAVIGATION_ENDED = 'NAVIGATION_ENDED';
export const NAVIGATION_INITIATED = 'NAVIGATION_INITIATED';
